language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-21

before_script:
  # Create and start emulator
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi x86
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew app:check --stacktrace
  - ./gradlew app:test --stacktrace
  - ./gradlew app:connectedAndroidTestMockWebServerPiDebug --info --stacktrace
